#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENTS_BIN="$HOME/.agents/bin"
TARGET="$AGENTS_BIN/codex"

usage() {
  cat <<EOF
Usage: codex-shim-install.sh [function|install|remove|status]

Prints the recommended shell function for agmsg Codex monitor mode.
With no subcommand, prints the function.

The optional global PATH shim can still be installed at:
  $TARGET

The function and PATH shim both route only interactive Codex launches through
agmsg's monitor bridge when the current project is in Codex monitor mode.
EOF
}

is_agmsg_shim() {
  [ -f "$TARGET" ] && grep -q "Optional Codex entrypoint shim for agmsg monitor mode" "$TARGET" 2>/dev/null
}

# Prints the skill script dir baked into the currently-installed shim (empty
# if there is none, or it is not an agmsg shim). This is the install that
# "owns" the shim: the one whose codex-shim.sh it execs into and whose
# storage/drivers every Codex launch through it will resolve.
#
# Reads a DEDICATED comment line (`# agmsg-shim-owner: <dir>`, written by
# `install` below) via plain string extraction -- never eval, and never the
# executable `export AGMSG_CODEX_SHIM_SCRIPT_DIR=...` line the shim itself
# needs at runtime. is_agmsg_shim matching only proves the marker STRING is
# present; it says nothing about the rest of the file's contents, which on a
# local, single-user path like this one could have been hand-edited after the
# fact. Evaling anything sourced from it -- as an earlier version of this
# function did -- turns a read-only `status` call into an arbitrary-code-
# execution path for whoever can write $TARGET (security review finding).
# Plain text extraction has no such path regardless of what the line contains.
shim_owner_script_dir() {
  is_agmsg_shim || return 0
  sed -n 's/^# agmsg-shim-owner: //p' "$TARGET" 2>/dev/null | head -1
}

shell_quote() {
  printf '%q' "$1"
}

cmd="${1:-function}"
case "$cmd" in
  -h|--help)
    usage
    ;;
  function|print-function|shell-function)
    cat <<EOF
# agmsg Codex monitor: put this in your interactive shell profile.
codex() {
  $(shell_quote "$SCRIPT_DIR/codex-shim.sh") "\$@"
}
EOF
    ;;
  install)
    mkdir -p "$AGENTS_BIN"
    if [ -e "$TARGET" ] && ! is_agmsg_shim; then
      echo "codex-shim-install: refusing to overwrite existing $TARGET" >&2
      echo "codex-shim-install: move it aside or remove it first" >&2
      exit 1
    fi
    # The shim path is one file shared by every install on the machine (#553):
    # whichever install's `install` ran last wins, and every Codex launch
    # through the shim then dispatches into ITS drivers/storage — silently,
    # since nothing here previously recorded whose the existing one was. Refuse
    # to hand it to a different skill dir without an explicit ask, naming which
    # install currently owns it so the caller can decide (re-run with
    # AGMSG_CODEX_SHIM_FORCE=1 to reclaim it, or leave it alone).
    owner="$(shim_owner_script_dir)"
    if [ -n "$owner" ] && [ "$owner" != "$SCRIPT_DIR" ] && [ "${AGMSG_CODEX_SHIM_FORCE:-}" != "1" ]; then
      echo "codex-shim-install: $TARGET is owned by a different install:" >&2
      echo "  $owner" >&2
      echo "codex-shim-install: refusing to repoint it at $SCRIPT_DIR" >&2
      echo "codex-shim-install: to claim it for THIS install instead, re-run with AGMSG_CODEX_SHIM_FORCE=1 --" >&2
      echo "codex-shim-install: every Codex launch that goes through the shim will then dispatch into" >&2
      echo "codex-shim-install: $SCRIPT_DIR instead of $owner" >&2
      exit 1
    fi
    {
      echo "#!/usr/bin/env bash"
      echo "set -euo pipefail"
      echo ""
      echo "# Optional Codex entrypoint shim for agmsg monitor mode."
      echo "# Generated by agmsg. Dispatches to the installed skill script."
      # Comment, never executed: the ownership marker shim_owner_script_dir
      # reads with plain text extraction, not eval. Kept separate from the
      # export line below, which is real, executable, runtime-required state
      # for codex-shim.sh, quoted for shell re-use rather than safe display.
      echo "# agmsg-shim-owner: $SCRIPT_DIR"
      echo ""
      echo "export AGMSG_CODEX_SHIM_WRAPPER=1"
      echo "export AGMSG_CODEX_SHIM_SCRIPT_DIR=$(shell_quote "$SCRIPT_DIR")"
      echo "export AGMSG_CODEX_SHIM_TARGET=$(shell_quote "$TARGET")"
      echo "exec $(shell_quote "$SCRIPT_DIR/codex-shim.sh") \"\$@\""
    } > "$TARGET"
    chmod +x "$TARGET"
    if [ "${AGMSG_CODEX_SHIM_INSTALL_QUIET:-}" != "1" ]; then
      echo "installed: $TARGET"
      case ":$PATH:" in
        *":$AGENTS_BIN:"*) ;;
        *)
          echo "note: this optional global shim needs $AGENTS_BIN before the real Codex binary on PATH"
          ;;
      esac
    fi
    ;;
  remove|uninstall)
    if is_agmsg_shim; then
      rm -f "$TARGET"
      echo "removed: $TARGET"
    elif [ -e "$TARGET" ]; then
      echo "codex-shim-install: $TARGET exists but is not the agmsg shim; leaving it untouched" >&2
      exit 1
    else
      echo "not installed: $TARGET"
    fi
    ;;
  status)
    if is_agmsg_shim; then
      echo "installed: $TARGET"
      # A second, separate line, not appended to the first. The "installed:"
      # prefix a caller matches on is unchanged either way, but a caller
      # piping this straight into `grep -q` (rather than capturing it first)
      # can still break under `pipefail` once there is a second line at all —
      # see install.sh's own callers for why, and capture before grep there.
      owner="$(shim_owner_script_dir)"
      if [ -n "$owner" ]; then
        if [ "$owner" = "$SCRIPT_DIR" ]; then
          echo "owner: this install ($owner)"
        else
          echo "owner: a different install ($owner)"
        fi
      fi
    else
      echo "not installed: $TARGET"
    fi
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
